- include/boost/mpi/detail/forward_skeleton_iarchive.hpp
- include/boost/mpi/detail/forward_skeleton_oarchive.hpp
- include/boost/mpi/detail/ignore_skeleton_oarchive.hpp
There were several errors when compiling with MSVC 14 and --build-type=complete because of wrong function signatures.
> Fix compilation

- include/boost/mpi/communicator.hpp
- include/boost/mpi/detail/binary_buffer_iprimitive.hpp
- include/boost/mpi/detail/binary_buffer_oprimitive.hpp
- include/boost/mpi/detail/forward_iprimitive.hpp
- include/boost/mpi/detail/forward_oprimitive.hpp
- include/boost/mpi/detail/ignore_iprimitive.hpp
- include/boost/mpi/detail/ignore_oprimitive.hpp
- include/boost/mpi/detail/mpi_datatype_primitive.hpp
- include/boost/mpi/detail/packed_iprimitive.hpp
- include/boost/mpi/detail/packed_oprimitive.hpp
Commit e3b67eb299b070edb32c2eb5da76653b4ed9cf5e in Boost.Serialization
renames serialization::array to serialization::array_wrapper.
> Fix: adapt to renaming of serialization::array_wrapper

- build/Jamfile.v2
- doc/Jamfile.v2
- doc/mpi.qbk
- include/boost/mpi/cartesian_communicator.hpp
- include/boost/mpi/communicator.hpp
- src/cartesian_communicator.cpp
- src/communicator.cpp
- test/Jamfile.v2
- test/cartesian_topology_test.cpp
This is a tentative implementation of cartesian communicator with associated documentation and test.
As far as the documentation is concerned, I just added the C mapping and the doxygen.
There are certainly a few issues. On point for which I am not sure about what to do is the topology description which in the C API id usually represented through 2 array (one for the dimensions, one for the periodicity). I choosed to represent it as a sequence of itermediate object (cartesian_dimension) representing a pair<int,bool> {dimension, periodic). The idea beeing that, using C++11ish syntax, it would give something like:
cartesian_communicator( { {2, true}, {3, false}} );
Note that the class does not use C++11 features (at least I don;t think so).
I choose not to templatize the class on the grid …
> Cartesian communicator

- include/boost/mpi/collectives/scatter.hpp
According to:
http://mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf
input data on Scatter should be passed as a pointer to const. Open MPI miss that const which invalidate the implicit conversion.
Should fix this one:
[Sandia-intel-16.0 - mpi - scatter_test-17 / intel-linux](http://www.boost.org/development/tests/develop/developer/output/Sandia-intel-16-0-boost-bin-v2-libs-mpi-test-scatter_test-17-test-intel-linux-debug-threading-multi.html)
> workaround an Open MPI bug:

- include/boost/mpi/python/serialize.hpp
The `auto_ptr` would use `delete p` to free an array allocated with `operator new[]`, which could result in heap corruption. Replaced it with `scoped_array`.
As an additional bonus, this gets rid of the warnings about using a deprecated component in C++11 mode.
> Fix incorrect usage of auto_ptr to free an array

- include/boost/mpi/detail/mpi_datatype_primitive.hpp
- include/boost/mpi/detail/packed_iprimitive.hpp
- include/boost/mpi/detail/packed_oprimitive.hpp
Several Boost.MPI headers include `<boost/serialization/detail/get_data.hpp>` which was removed by https://github.com/boostorg/serialization/commit/d558b6da917ecae1036adf9b22a0741c78f627ff
This causes multiple build failures with the current snapshot at http://downloads.sourceforge.net/boost/boost_1_63_0.tar.bz2
````
    "g++"  -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fn
o-strict-aliasing -Wno-unused-local-typedefs -pthread -fPIC  -DBOOST_ALL_NO_LIB=1 -DBOOST_GRAPH_DYN_LINK=1 -DBOOST_GRAPH_NO_LIB=1 -DNDEBUG  -I"." -I"/usr/include/openmpi-x86_64" -I"libs/graph_parallel/src" -c -o "openmpi-x86_64/boost/bin …
```
> Replace boost::serialization::detail::get_data function.

- include/boost/mpi/python/serialize.hpp
The `<boost/mpi/python/serialize.hpp>` header uses `serialization::make_array` without including the right header, and so the snapshot at http://downloads.sourceforge.net/boost/boost_1_63_0.tar.bz2 fails to build.
> Add header for serialization::make_array

- include/boost/mpi/communicator.hpp
Just remove code between #if 0 that has been here for some time, and related to a functionality since then implemented in another way.
> Delete now clearly obsolete #if 0ed code.

- include/boost/mpi/detail/antiques.hpp
- include/boost/mpi/detail/mpi_datatype_primitive.hpp
- include/boost/mpi/detail/packed_iprimitive.hpp
- include/boost/mpi/detail/packed_oprimitive.hpp
All in the title.
1.64 was not building on most platform and was working for the wrong reason on others (presence of /usr/include/boost/serialization/detail/get_data.hpp")
> Do not include serialization/detail/get_data.hpp as it disapear in 1.64.

- build/Jamfile.v2
This fixes Boost.MPI 1.64 compilation:
```
gcc.compile.c++ bin.v2/libs/mpi/build/gcc-6.3.0/release/debug-symbols-on/threading-multi/python/serialize.o
In file included from ./boost/python/detail/prefix.hpp:13:0,
from ./boost/python/ssize_t.hpp:9,
from ./boost/python/object.hpp:8,
from ./boost/mpi/python/serialize.hpp:25,
from libs/mpi/src/python/serialize.cpp:13:
./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
^
compilation terminated.
"g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -g -pthread -fPIC -m64 -std=gnu++0x -DBOOST_ALL_NO_LIB=1 -DBOOST_MPI_DYN_LINK=1 -DBOOST_MPI_PYTHON_DYN_LINK=1 -DBOOST_MPI_PYTHON_SOURCE=1 -DBOOST_PYTHON_DYN_LINK=1 -DNDEBUG  -I"." -I"/usr/lib/x86_64-linux-gnu/ope
...failed gcc.compile.c++ …
```
> Fix mpi-python component compilation.

- include/boost/mpi/detail/antiques.hpp
- src/point_to_point.cpp
Some (old) MPI implementation have a non conforming signature w.r.t.
This is the case for **MPI_Send**, those signature should be, according to the [standard](http://mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf#56):
{{{
int MPI_Send(const void* buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm)
}}}
> Add const conversion to accomodate open MPI 1.6

- include/boost/mpi/operations.hpp
std::binary_function was removed in C++17 and is no longer available while compiling with MS Visual Studio 2017
> Remove deprecated std::binary_function

- build/Jamfile.v2
- include/boost/mpi/error_string.hpp
- include/boost/mpi/exception.hpp
- src/error_string.cpp
- src/exception.cpp
We are missing a clean conversion from MPI error code to strings.
This is a C++ version of MPI_Error_string
> Add MPI error code to string convertion

- include/boost/mpi/cartesian_communicator.hpp
- test/cartesian_topology_test.cpp
Modify the signature of the move ctor to avoid infinite loop.
Test move ctor on cartesian topology.
refs #57
> Bug with move ctor signature

- build/Jamfile.v2
Just build mpi-python against current boost_python, not boostpython2|3
Looks like boost_python has moved on and stopped providing
boost_python2 and boost_python3 libraries. Possibly a regression in
boost_python, or possibly new world order which mpi should adapt to.
Fixes build: --with-python --with-mpi --python-buildid=py36 python=3.6
> Fix jam py3

- build/Jamfile.v2
Previously python-tags were specified, but actually ineffective as
python-tag is not an available rule. Copy&Paste python-tag rule from
libs/python/Jamfile.
This now correctly creates `libboost_mpi_python27.so` to match `libboost_python27.so` & `libboost_numpy27.so`.
> Complete jamfile fixes for python-tag.

- include/boost/mpi/collectives/all_reduce.hpp
- include/boost/mpi/collectives/reduce.hpp
- include/boost/mpi/collectives/scan.hpp
- include/boost/mpi/operations.hpp
Try to make sure user's operators are stateless, and do not use their state if any.
refs #68
> dangling pointer to custom operation in collectives

- include/boost/mpi/detail/antiques.hpp
If the standard library is configured to do range checks (`-D_GLIBCXX_ASSERTIONS`), accessing the zeroth element of a vector to get its address triggers an assertion.
This issue was discovered in https://github.com/espressomd/espresso/issues/2507, where `boost::mpi::detail::dispatch_scatter_sendbuf` runs into it.
> mpi::detail::c_data needs to check for empty vectors

- include/boost/mpi/detail/offsets.hpp
with MSVC, using templates that use sizes2offsets (such as gather) requires
sizes2offsets to be exported
> BOOST_MPI_DECL for sizes2offsets

- include/boost/mpi/operations.hpp
- src/environment.cpp
In C++17, `std::uncaught_exception` is deprecated in favor of `std::uncaught_exceptions`. Use portable `uncaught_exceptions` implementation from Boost.Core, which is also available for C++03.
This fixes gcc 8 warnings about using deprecated features in C++17 mode.
> Use uncaught_exceptions from Boost.Core to avoid C++17 warnings

- build/Jamfile.v2
This fixes mpi plugins for Python not being built and installed.
> Add MPI Python libs to install target

- include/boost/mpi/detail/request_handlers.hpp
Hi boost developers.
After to have upgraded my boost version to 1.69 and I have this error :
```
communicator.hpp:1914: static optional<boost::mpi::status> boost::mpi::request::handle_dynamic_primitive_array_irecv(boost::mpi::request *, boost::mpi::request::request_action) [T = int, A = std::allocator<int>]: Assertion `_check_result == MPI_SUCCESS' failed.
```
The issue can be reproduce with this code : 
```
mpi::communicator comm;
int rank = comm.rank();
std::vector<int> data;
std::vector< mpi::request> reqs;
if ( rank == 0 )
{
for ( int i=0;i<10;++i )
data.push_back( i );
reqs.push_back( comm.isend(1, 0, data) );
}
else if ( rank == 1 )
{
reqs.push_back( comm.irecv(0, 0, data) );
}
mpi::wait_all( reqs.begin(), reqs.end() );
if ( rank == 1 )
{
for ( int i=0;i<data.size();++i )
std::cout …
```
> Fix error when mpi::wait_all is called with data of type std::vector

- .travis.yml
- include/boost/mpi/collectives/all_reduce.hpp
- include/boost/mpi/collectives/all_to_all.hpp
- include/boost/mpi/collectives/gatherv.hpp
- include/boost/mpi/collectives/reduce.hpp
- include/boost/mpi/collectives/scatter.hpp
- include/boost/mpi/collectives/scatterv.hpp
- include/boost/mpi/detail/binary_buffer_iprimitive.hpp
- include/boost/mpi/detail/binary_buffer_oprimitive.hpp
- include/boost/mpi/detail/mpi_datatype_primitive.hpp
- include/boost/mpi/detail/packed_iprimitive.hpp
- include/boost/mpi/detail/packed_oprimitive.hpp
- include/boost/mpi/detail/request_handlers.hpp
- include/boost/mpi/graph_communicator.hpp
- include/boost/mpi/group.hpp
- include/boost/mpi/nonblocking.hpp
- src/cartesian_communicator.cpp
- test/block_nonblock_test.cpp
There are multiple places in the library where a pointer to the memory managed by a vector by taking the address of the first element. This leads to undefined behavior if the vector is empty (eg there is no first element), which has caused problems downstream. For example some standard libraries have asserts for this. This patch is a modified version of a patch created by @mkuron which switches all the places that we found to `detail::c_data`, which already existed in the library.
(Please note that not all of the replacements are needed because in some places the vector can not
be empty, but I find the function call also more idiomatic and readable, and easier to replace when support for C++03 is dropped)
> Avoid access of front element in empty vectors

- include/boost/mpi/nonblocking.hpp
Analogously to MPI_REQUEST_NULL being the neutral element to MPI_Wait(), a null request should gracefully be handled also by wait_all.
Currently (boost 1.73) this deadlocks:
```c++
#include <boost/mpi.hpp>
#include <boost/mpi/nonblocking.hpp>
#include <vector>
int main()
{
boost::mpi::environment env;
std::vector<boost::mpi::request> req(1);
boost::mpi::wait_all(req.begin(), req.end());
}
```
(You may add this or derivatives of it as a test case under the boost license.)
This PR fixes this issue by treating inactive requests as completed.
> Waitall: Handle null (default constructed) requests

- build/Jamfile.v2
On Windows, all code using Python has to link to the Python import library.
`python_for_extensions` is a target defined by Boost.Build to provide the Python include paths, and on Windows, the Python import library, as usage requirements.
> Fix build boost_mpi_python on Windows

- meta/libraries.json
The "cxxstd" json field is being added to each Boost library's meta json information for libraries in order to specify the minumum C++ standard compilation level. The value of this field matches one of the values for 'cxxstd' in Boost.Build. The purpose of doing this is to provide information for the Boost website documentation for each library which will specify the minimum C++ standard compilation that an end-user must employ in order to use the particular library. This will aid end-users who want to know if they can successfully use a Boost library based on their C++ compiler's  compilation level, without having to search the library's documentation to find this out.
> [skip ci] Add "cxxstd" json field.

- include/boost/mpi/environment.hpp
- src/environment.cpp
Closes https://github.com/boostorg/mpi/issues/133 .
> Don't use MPI constants as compile-time constants

- build/__init__.py
Hi @aminiussi 
we have been carrying this patch in Gentoo for ages, and would like to upstream it. The current import statements are still from the Python 2/pre-PEP328 days. In Gentoo, the Boost.MPI python layout looks like:
```
$ tree /usr/lib/python3.11/site-packages/boost/
/usr/lib/python3.11/site-packages/boost/
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-311.opt-1.pyc
│   ├── __init__.cpython-311.opt-2.pyc
│   └── __init__.cpython-311.pyc
└── mpi.so
2 directories, 5 files
```
and in order for `__init__.py` to import the CPython module, you need to use PEP328-style absolute imports on modern python installations.
> PEP 328 import

- build.jam
- build/Jamfile.v2
- doc/Jamfile.v2
- test/Jamfile.v2
This is part of the effort to make the Boost libraries "modular" for build and consumption. See https://lists.boost.org/Archives/boost/2024/01/255704.php and https://github.com/grafikrobot/boost-b2-modular/blob/b2-modular/README.adoc for more information.
This PR depends on the following other PRs being merged to both develop and master branches of the respective repos:
- https://github.com/boostorg/boost/pull/854
This PR will be changed to ready for review, i.e. not draft, when the above are merged. Do not merge this one until that time.
> Add support for modular build structure.

- build.jam
Closes https://github.com/boostorg/mpi/issues/161
> Remove boost_python from global dependency list
